### ISSUE TITLE
DevToys crashes on Base64 Text 

### ISSUE THREAD

**Issue by chargerback-ron** [veler/DevToys#757]
### Description

When I select Encoders / Decoders, then Base64 Text, I am unable to paste anything in. DevToys just closes. Experimenting with it, the behavior is the same if I don't attempt to paste anything either; after a few seconds DevToys just closes. I have Smart detection turned off. The Base64 string I wanted to decode is only 28 bytes.

### Steps To Reproduce

1. Open DevToys
2. Select Encoders / Decoders
3. Select Base64 Text
4. Wait 30 seconds

That's all I have to do for it to crash. Oh, I also noticed that if I Alt-Tab away, I cannot Alt-Tab back to DevToys with Base64 Text open.

### Expected behavior

I expect it not to crash.

### DevToys Version

Version 1.0.10.0 | X64 | RELEASE | b949a18 | b949a18

### Relevant Assets/Logs

Edition	Windows 10 Pro
Version	22H2
Installed on	‎6/‎11/‎2020
OS build	19045.2604
Experience	Windows Feature Experience Pack 120.2212.4190.0

Device name	XXX-XXX
Processor	AMD Ryzen 7 2700X Eight-Core Processor            4.00 GHz
Installed RAM	32.0 GB
Device ID	XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
Product ID	00330-71301-76829-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

**Comment by veler** [comment]
Hi,
Thanks for your report. It might be related to #755.
After the app crashed, can you please start it again and go to `Settings > Open logs` and paste the logs here?

**Comment by chargerback-ron** [comment]
Hello - here are the logs.

# - [03/22/2022 12:00:20]
Feature name: Failed to load a file into a code editor
Custom message: 
Exception message: No mapping for the Unicode character exists in the target multi-byte code page.

No mapping for the Unicode character exists in the target multi-byte code page.

Exception stack trace:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at DevToys.UI.Controls.CustomTextBox.<OpenFileButton_Click>d__83.MoveNext() + 0x2af


# - [02/16/2023 14:10:05]
Feature name: Unhandled problem
Custom message: 
Exception message: Access is denied. (Exception from HRESULT: 0x80070005)
Exception stack trace:
   at System.Runtime.InteropServices.McgMarshal.ThrowOnExternalCallFailed(Int32, RuntimeTypeHandle) + 0x21
   at __Interop.ComCallHelpers.Call(__ComObject, RuntimeTypeHandle, Int32, Color) + 0xbd
   at __Interop.ForwardComStubs.Stub_66[TThis](__ComObject, Color, Int32) + 0x2d
   at Windows.UI.Text.ITextCharacterFormat__Impl.Dispatcher.global::Windows.UI.Text.ITextCharacterFormat.put_BackgroundColor(Color) + 0x1e
   at DevToys.UI.Controls.CustomTextBox.SetHighlights(IEnumerable`1) + 0x473
   at DevToys.UI.Controls.CustomTextBox.OnActualThemeChanged(FrameworkElement, Object) + 0xc
   at Windows.Foundation.TypedEventHandler`2.Invoke(TSender, TResult) + 0x2e
   at __Interop.Intrinsics.HasThisCall__33[TArg0](Object, IntPtr, Object, TArg0) + 0x36
   at DevToys!<BaseAddress>+0x12c2c5e


# - [02/16/2023 14:10:20]
Feature name: Unhandled problem
Custom message: 
Exception message: Access is denied. (Exception from HRESULT: 0x80070005)
Exception stack trace:
   at System.Runtime.InteropServices.McgMarshal.ThrowOnExternalCallFailed(Int32, RuntimeTypeHandle) + 0x21
   at __Interop.ComCallHelpers.Call(__ComObject, RuntimeTypeHandle, Int32, Color) + 0xbd
   at __Interop.ForwardComStubs.Stub_66[TThis](__ComObject, Color, Int32) + 0x2d
   at Windows.UI.Text.ITextCharacterFormat__Impl.Dispatcher.global::Windows.UI.Text.ITextCharacterFormat.put_BackgroundColor(Color) + 0x1e
   at DevToys.UI.Controls.CustomTextBox.SetHighlights(IEnumerable`1) + 0x473
   at DevToys.UI.Controls.CustomTextBox.OnActualThemeChanged(FrameworkElement, Object) + 0xc
   at Windows.Foundation.TypedEventHandler`2.Invoke(TSender, TResult) + 0x2e
   at __Interop.Intrinsics.HasThisCall__33[TArg0](Object, IntPtr, Object, TArg0) + 0x36
   at DevToys!<BaseAddress>+0x12c2c5e

**Comment by chargerback-ron** [comment]
It doesn't appear to be writing a log for the crash. It is very easy to reproduce, however. Just open the app in "Dark Mode", then open the Base64 Text decode. Wait a few seconds, and the app closes.

**Comment by AVTPJ** [comment]
Can confirm that it doesn't write anything to log on crash. Just quits.

Can also confirm that it only happens in Dark Mode.

**Comment by veler** [comment]
This is so weird. Haven't been able to reproduce it on my side so far.

**Comment by martinjanocko** [comment]
Hello, I am also affected by this issue and tried to poke a bit in code. Don't have any experience with Windows apps, but this is what I can see, maybe it helps pinpointing the actual issue.

As far as i can tell this happens in `DevToys-1.0.10.0\src\dev\impl\DevToys\UI\Controls\CustomTextBox.xaml.cs:370` if the range to edit the background and foreground color is selected from Text that has Text.Length of 0. 
![image](https://user-images.githubusercontent.com/91722334/224303276-8af69e86-f601-4cbf-bb12-a69d81effb2a.png)

If you check for the Text.Length to be > 0, the crash no longer occurs.

Stack trace:
```
Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))

   at Windows.UI.Text.ITextCharacterFormat.put_BackgroundColor(Color value)
   at DevToys.UI.Controls.CustomTextBox.SetHighlights(IEnumerable`1 spans) in DevToys-1.0.10.0\src\dev\impl\DevToys\UI\Controls\CustomTextBox.xaml.cs:line 370
   at DevToys.UI.Controls.CustomTextBox.OnActualThemeChanged(FrameworkElement sender, Object args) in DevToys-1.0.10.0\src\dev\impl\DevToys\UI\Controls\CustomTextBox.xaml.cs:line 600
```

**Comment by veler** [comment]
Duplicate with #757

**Comment by veler** [comment]
My bad. I meant #755
